### PR TITLE
chore: release 0.1.0

### LINKED ISSUE #290: Release a new version
There's been a suite of recent changes to `substrait-validator`, and it would be useful to release a new version, as mentioned briefly [here](https://github.com/substrait-io/substrait-validator/pull/274#pullrequestreview-2355811859).

I'm opening this issue to raise the question - what features or changes (outside [the documented release](https://github.com/substrait-io/substrait-validator/blob/1f351c63fda50754958c635e6b7ca0f210bebfa8/RELEASE.md) chores) do we want before we're ready for a new version?

### PR DESCRIPTION
**Pull request by wackywendell**
### This PR

Closes #290.

This PR is:
1. First commit is purely codegen from running `python ci/version.py set 0.1.0`.
2. Second commit updates the repository info in `Cargo.toml`, which [appears on crates.io](https://crates.io/crates/substrait-validator)
3. Third commit updates the substrait compatibility matrix in the README

I went with 0.1.0 because the jump in substrait version supported like more than just a patch version change, although I'm not sure it matters pre-1.0; if others have opinions, it would be trivial to switch this to 0.0.12 instead.

### Releasing

After this is merged, based on what I [saw earlier](https://github.com/substrait-io/substrait-validator/issues/290#issuecomment-2458185972), I think all we need to do is add a tag (e.g. [via the Github web interface](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)) [of the form](https://github.com/substrait-io/substrait-validator/blob/0b1fbbba0f04752bd593260fb55b3cd599690481/.github/workflows/rust.yml#L7) `v*.*.*` and CI should take it from there - building and [publishing to crates.io](https://github.com/substrait-io/substrait-validator/blob/0b1fbbba0f04752bd593260fb55b3cd599690481/.github/workflows/rust.yml#L137) and [to PyPI](https://github.com/substrait-io/substrait-validator/blob/0b1fbbba0f04752bd593260fb55b3cd599690481/.github/workflows/python.yml#L121-L127).

### Followup

1. Fix any issues with CI if release doesn't go smoothly
4. [Update the docs](https://github.com/substrait-io/substrait-validator/blob/1f351c63fda50754958c635e6b7ca0f210bebfa8/RELEASE.md) to clarify that adding a tag is enough to trigger an automated release.

### CODE REVIEW

**Review by mbrobbel — COMMENTED** [review]
Thanks for initiating this.

One question: can you also update the https://github.com/substrait-io/substrait-validator?tab=readme-ov-file#substrait-version-support section in this PR?

**Review by mbrobbel — APPROVED** [review]

**Comment by mbrobbel** [comment]
Rust: https://github.com/substrait-io/substrait-validator/actions/runs/11711071490
Python: https://github.com/substrait-io/substrait-validator/actions/runs/11711071506

🤞

**Comment by wackywendell** [comment]
> Looks like we need a fix for the Python wheel artifact issue.

Hm, yes. I'm not quite sure what the problem is - it might be that we have N jobs attempting to upload `wheels.zip`, and only one can succeed? So perhaps they should each be attempting to upload `wheels-${ARCH}-${PYTHON_VERSION}`?

**Comment by mbrobbel** [comment]
This was a breaking change in the `v4` release of the download/upload actions: https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes

There are some suggestions in https://github.com/actions/upload-artifact/issues/480.

**Comment by wackywendell** [comment]
Judging from [here](https://github.com/actions/upload-artifact?tab=readme-ov-file#not-uploading-to-the-same-artifact), it looks like dependabot's [upgrade of `actions/upload-artifact`](https://github.com/substrait-io/substrait-validator/pull/112) from 3 to 4 led to this:

> Unlike earlier versions of `upload-artifact`, uploading to the same artifact via multiple jobs is _not_ supported with v4
>
> …
> 
> Artifact names must be unique since each created artifact is idempotent so multiple jobs cannot modify the same artifact.

I'm happy to make a PR here, although you know this part of the code better than I do, @mbrobbel!

**Pull request merged**
