### PR TITLE
chore(version): Release 0.1.1

### PR DESCRIPTION
**Pull request by wackywendell**
A patch release following #297 to get Python out (#296).

### CODE REVIEW

**Review by mbrobbel — APPROVED** [review]
Thanks.

**Comment by wackywendell** [comment]
I'm really hoping this works 🤞  - if this fails at the "Upload to PyPI" stage that would be sad!

**Comment by mbrobbel** [comment]
PyPi upload failed: https://github.com/substrait-io/substrait-validator/actions/runs/11749326512/job/32735746500#step:5:44. I'll ask Jeroen to verify his email.

**Comment by mbrobbel** [comment]
Fixed 🎉.

**Pull request merged**
